name: Deploy-Staging-Production

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: stg
      url: https://yahoo.co.jp
    steps:
      - run: echo deploy staging
      - run: echo secret ${{ secrets.SAMPLE_SECRET }}
      - run: date
  
  deploy_production:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://google.com
    steps:
      - run: echo deploy production
      - run: echo secret ${{ secrets.SAMPLE_SECRET }}
      - run: date
